# Generated by Django 2.1 on 2018-08-21 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testruns', '0016_remove_auto_update_run_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaltestcaserun',
            name='environment_id',
        ),
        migrations.RemoveField(
            model_name='historicaltestrun',
            name='environment_id',
        ),
        migrations.RemoveField(
            model_name='testcaserun',
            name='environment_id',
        ),
        migrations.RemoveField(
            model_name='testrun',
            name='environment_id',
        ),

        migrations.RemoveField(
            model_name='envrunvaluemap',
            name='run',
        ),
        migrations.RemoveField(
            model_name='envrunvaluemap',
            name='value',
        ),
        migrations.RemoveField(
            model_name='testrun',
            name='env_value',
        ),
        migrations.DeleteModel(
            name='EnvRunValueMap',
        ),
    ]
